const sequelize = require('../config/database');

async function fixIndexes() {
  try {
    await sequelize.authenticate();
    console.log('DB Connected.');

    const tablesToCheck = ['players', 'realms'];

    for (const tableName of tablesToCheck) {
        console.log(`\nChecking indexes for table: ${tableName}`);
        try {
            const [indexes] = await sequelize.query(`SHOW INDEX FROM \`${tableName}\`;`);
            
            // Filter indexes to find redundant ones (those ending with _number)
            const redundantIndexes = indexes.filter(idx => {
                // Keep PRIMARY and the original index (assuming original doesn't end in _\d+)
                // Or simpler: if key_name matches /_\d+$/ it's likely a duplicate generated by sequelize
                // Check if key_name is not PRIMARY and matches the pattern or is a duplicate
                
                // Let's print what we are planning to drop
                return idx.Key_name !== 'PRIMARY' && (idx.Key_name.match(/_\d+$/) || idx.Key_name.startsWith(idx.Column_name + '_'));
            });

            // We need to be careful. sequelize might name the first index "username_unique" or just "username".
            // In the log we saw "username" and then "username_2".
            // So we want to keep "username" and drop "username_2", "username_3"...
            
            // Group by column name to be safer?
            // In the log: 
            // - username (username)
            // - username_2 (username)
            
            const indexesToDrop = [];
            const seenColumns = new Set();
            
            // Sort indexes by name length or just alphabetical to process base name first?
            // Actually, in the log, the base one is "username". The duplicates are "username_2".
            
            // Let's iterate and collect names to drop.
            indexes.forEach(idx => {
                if (idx.Key_name === 'PRIMARY') return;
                
                // If it looks like a duplicate (ends with _\d+)
                if (/_\d+$/.test(idx.Key_name)) {
                    indexesToDrop.push(idx.Key_name);
                }
            });

            // Remove duplicates from the list (SHOW INDEX returns a row per column in index, but these are single column indexes)
            const uniqueIndexesToDrop = [...new Set(indexesToDrop)];

            console.log(`Found ${uniqueIndexesToDrop.length} redundant indexes to drop in ${tableName}.`);
            
            for (const indexName of uniqueIndexesToDrop) {
                console.log(`Dropping index ${indexName}...`);
                await sequelize.query(`DROP INDEX \`${indexName}\` ON \`${tableName}\`;`);
            }
            
        } catch (e) {
            console.error(`Error processing ${tableName}:`, e.message);
        }
    }

    console.log('\nIndex cleanup complete.');
    process.exit(0);
  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

fixIndexes();
